package warframe_market_prime_trash_buyer

// ProfitableItemNames — список предметов, которые считаются выгодными для покупки.
var ProfitableItemNames = []string{
	"Akbronco Prime Link",
	"Astilla Prime Stock",
	"Atlas Prime Chassis Blueprint",
	"Afuris Prime Link",
	"Baza Prime Barrel",
	"Braton Prime Receiver",
	"Burston Prime Barrel",
	"Corvas Prime Blueprint",
	"Dethcube Prime Carapace",
	"Dual Keres Prime Blueprint",
	"Garuda Prime Chassis Blueprint",
	"Gara Prime Neuroptics Blueprint",
	"Guandao Prime Blueprint",
	"Harrow Prime Blueprint",
	"Harrow Prime Neuroptics Blueprint",
	"Inaros Prime Chassis Blueprint",
	"Karyst Prime Handle",
	"Khora Prime Chassis Blueprint",
	"Knell Prime Receiver",
	"Magnus Prime Receiver",
	"Nagantaka Prime Stock",
	"Nidus Prime Blueprint",
	"Ninkondi Prime Chain",
	"Orthos Prime Blueprint",
	"Pandero Prime Barrel",
	"Panthera Prime Stock",
	"Redeemer Prime Blueprint",
	"Scourge Prime Handle",
	"Stradavar Prime Barrel",
	"Tatsu Prime Blade",
	"Tekko Prime Blueprint",
	"Titania Prime Neuroptics Blueprint",
	"Volnus Prime Head",
	"Zakti Prime Barrel",
}
